const COUNTRIES = [

{
  "name":"Afghanistan",
  "capital": "Kabul",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Pashto", "Dari"],
  "borders": ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
},
{
  "name": "Albania",
  "capital": "Tirana",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Albanian"],
  "borders": ["MNE", "GRC", "MKD", "KOS"],
},
{
  "name": "Algeria",
  "capital": "Algiers",
  "region": "Africa",
  "subregion": "Northern Africa",
  "language": ["Arabic"],
  "borders": ["TUN", "LDY", "NER", "ESH", "MRT", "MLI", "MAR"],
},
{
  "name": "American Samoa",
  "capital": "Pago Pago",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["English", "Samoan"],
  "borders": [],
},
{
  "name": "Andorra",
  "capital": "Andorra la Vella",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Catalan"],
  "borders": ["FRA", "ESP"],
},
{
  "name": "Angola",
  "capital": "Luanda",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["Portuguese"],
  "borders": ["COG", "COD", "ZMB", "NAM"],
},
{
  "name": "Anguilla",
  "capital": "The Valley",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Antigua and Barbuda",
  "capital": "Saint John's",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Argentina",
  "capital": "Buenos Aires",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish"],
  "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
},
{
  "name": "Armenia",
  "nativeName": "\u0540\u0561\u0575\u0561\u057d\u057f\u0561\u0576",
  "capital": "Yerevan",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Armenian"],
  "borders": ["AZE", "GEO", "IRN", "TUR"],
},
{
  "name": "Aruba",
  "capital": "Oranjestad",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Dutch", "Papiamento"],
  "borders": [],
},
{
  "name": "Ascension Island",
  "capital": "Georgetown",
  "region": "Americas",
  "subregion": "South America",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Australia",
  "capital": "Canberra",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Austria",
  "capital": "Vienna",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["German"],
  "borders": ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
},
{
  "name": "Azerbaijan",
  "capital": "Baku",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Azerbaijani"],
  "borders": ["ARM", "GEO", "IRN", "RUS", "TUR"],
},
{
  "name": "Bahamas",
  "capital": "Nassau",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Bahrain",
  "capital": "Manama",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": [],
},
{
  "name": "Bangladesh",
  "capital": "Dhaka",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Bangla"],
  "borders": ["MMR", "IND"],
},
{
  "name": "Barbados",
  "capital": "Bridgetown",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Belarus",
  "capital": "Minsk",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Belarusian", "Russian"],
  "borders": ["LVA", "LTU", "POL", "RUS", "UKR"],
},
{
  "name": "Belgium",
  "capital": "Brussels",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["Dutch", "French", "German"],
  "borders": ["FRA", "DEU", "LUX", "NLD"],
},
{
  "name": "Belize",
  "capital": "Belmopan",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["English"],
  "borders": ["GTM", "MEX"],
},
{
  "name": "Benin",
  "capital": "Porto-Novo",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["French"],
  "borders": ["BFA", "NER", "NGA", "TGO"],
},
{
  "name": "Bermuda",
  "capital": "Hamilton",
  "region": "Americas",
  "subregion": "Northern America",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Bhutan",
  "capital": "Thimphu",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Dzongkha"],
  "borders": ["CHN", "IND"],
},
{
  "name": "Bolivia",
  "capital": "Sucre",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish", "Quechua", "Aymara", "Guaran\u00ed"],
  "borders": ["ARG", "BRA", "CHL", "PRY", "PRU"],
},
{
  "name": "Bonaire",
  "capital": "Kralendijk",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Dutch"],
  "borders": [],
},
{
  "name": "Bosnia and Herzegovina",
  "capital": "Sarajevo",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Bosnian", "Croatian", "Serbian"],
  "borders": ["HRV", "MNE", "SRB"],
},
{
  "name": "Botswana",
  "capital": "Gaborone",
  "region": "Africa",
  "subregion": "Southern Africa",
  "language": ["English", "Setswana"],
  "borders": ["NAM", "ZAF", "ZMB", "ZWE"],
},
{
  "name": "Brazil",
  "capital": "Bras\u00edlia",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Portuguese"],
  "borders": ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
},
{
  "name": "British Indian Ocean Territory",
  "capital": "Diego Garcia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["English"],
  "borders": [],
},
{
	"name": "British Virgin Islands",
	"capital": "Road Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Brunei",
	"capital": "Bandar Seri Begawan",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Malay"],
	"borders": ["MYS"],
},
{
	"name": "Bulgaria",
	"capital": "Sofia",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Bulgarian"],
	"borders": ["GRC", "MKD", "ROU", "SRB", "TUR"],
},
{
  "name": "Burkina Faso",
  "capital": "Ouagadougou",
	"region": "Africa",
  "subregion": "Western Africa",
	"language": ["French"],
	"borders": ["BEN", "CIV", "GHA", "MLI", "NER", "TGO"],
},
{
	"name": "Burundi",
	"capital": "Bujumbura",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Kirundi", "French"],
	"borders": ["COD", "RWA", "TZA"],
},
{
  "name": "Cambodia",
  "capital": "Phnom Penh",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "language": ["Khmer"],
  "borders": ["LAO", "THA", "VNM"],
},
{
  "name": "Cameroon",
  "capital": "Yaound\u00e9",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["French", "English"],
  "borders": ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"],
},
{
  "name": "Canada",
	"capital": "Ottawa",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["English", "French"],
	"borders": ["USA"],
},
{
	"name": "Cape Verde",
	"capital": "Praia",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["Portuguese"],
	"borders": [],
},
{
	"name": "Cayman Islands",
	"capital": "George Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Central African Republic",
	"capital": "Bangui",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["Sango", "French"],
	"borders": ["CMR", "TCD", "COD", "COG", "SSD", "SDN"],
},
{
	"name": "Chad",
	"capital": "N'Djamena",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["French", "Arabic"],
	"borders": ["CMR", "CAF", "LBY", "NER", "NGA", "SSD"],
},
{
	"name": "Chile",
  "capital": "Santiago",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish"],
  "borders": ["ARG", "BOL", "PER"],
},
{
	"name": "China",
  "capital": "Beijing",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Standard Chinese"],
	"borders": ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "PAK", "RUS", "TJK", "VNM"],
},
{
	"name": "Christmas Island",
	"capital": "Flying Fish Cove",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Cocos (Keeling) Islands",
	"capital": "West Island",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Colombia",
	"capital": "Bogot\u00e1",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["BRA", "ECU", "PAN", "PER", "VEN"],
},
{
	"name": "Comoros",
	"capital": "Moroni",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Comorian", "Arabic", "French"],
	"borders": [],
},
{
	"name": "Republic of the Congo",
	"capital": "Brazzaville",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["French"],
  "borders": ["AGO", "CMR", "CAF", "COD", "GAB"],
},
{
	"name": "Democratic Republic of the Congo",
	"capital": "Kinshasa",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["French"],
	"borders": ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"],
},
{
  "name": "Cook Islands",
	"capital": "Avarua",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["English", "Cook Islands M\u0101ori"],
	"borders": [],
},
{
	"name": "Costa Rica",
  "capital": "San Jos\u00e9",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["NIC", "PAN"],
},
{
	"name": "Croatia",
  "capital": "Zagreb",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Croatian"],
	"borders": ["BIH", "HUN", "MNE", "SRB", "SVN"],
},
{
	"name": "Cuba",
	"capital": "Havana",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Spanish"],
  "borders": [],
},
{
	"name": "Cura\u00e7ao",
	"capital": "Willemstad",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Dutch", "Papiamentu", "English"],
	"borders": [],
},
{
	"name": "Cyprus",
	"capital": "Nicosia",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Greek", "Turkish"],
	"borders": ["GBR"],
},
{
	"name": "Czech Republic",
  "capital": "Prague",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Czech"],
  "borders": ["AUT", "DEU", "POL", "SVK"],
},
{
	"name": "Denmark",
	"capital": "Copenhagen",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Danish"],
	"borders": ["DEU"],
},
{
	"name": "Djibouti",
	"capital": "Djibouti",
	"region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["French", "Arabic"],
	"borders": ["ERI", "ETH", "SOM"],
},
{
	"name": "Dominica",
	"capital": "Roseau",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Dominican Republic",
	"capital": "Santo Domingo",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Spanish"],
  "borders": ["HTI"],
},
{
	"name": "Ecuador",
	"capital": "Quito",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["COL", "PER"],
},
{
	"name": "Egypt",
	"capital": "Cairo",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic"],
	"borders": ["ISR", "LBY", "SDN"],
},
{
	"name": "El Salvador",
	"capital": "San Salvador",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["Castilian"],
  "borders": ["GTM", "HND"],
},
{
  "name": "Equatorial Guinea",
  "capital": "Malabo",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["Spanish", "French", "Portuguese"],
	"borders": ["CMR", "GAB"],
},
{
	"name": "Eritrea",
	"capital": "Asmara",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Tigrinya", "Arabic", "English"],
	"borders": ["DJI", "ETH", "SDN"],
},
{
	"name": "Estonia",
  "capital": "Tallinn",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Estonian"],
  "borders": ["LVA", "RUS"],
},
{
	"name": "Ethiopia",
  "capital": "Addis Ababa",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["Amharic"],
  "borders": ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"],
},
{
	"name": "Falkland Islands",
	"capital": "Stanley",
	"region": "Americas",
	"subregion": "South America",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Fiji",
  "capital": "Suva",
  "region": "Oceania",
  "subregion": "Melanesia",
  "language": ["English", "Fijian", "Fiji Hindi"],
	"borders": [],
},
{
	"name": "Finland",
  "capital": "Helsinki",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Finnish", "Swedish"],
  "borders": ["NOR", "SWE", "RUS"],
},
{
	"name": "France",
	"capital": "Paris",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["French"],
	"borders": ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
},
{
  "name": "French Guiana",
  "capital": "Cayenne",
  "region": "Americas",
  "subregion": "South America",
  "language": ["French"],
	"borders": ["BRA", "SUR"],
},
{
	"name": "French Polynesia",
	"capital": "Papeet\u0113",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["French"],
	"borders": [],
},
{
  "name": "Gabon",
  "capital": "Libreville",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["French"],
	"borders": ["CMR", "COG", "GNQ"],
},
{
  "name": "Gambia",
  "capital": "Banjul",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["English"],
  "borders": ["SEN"],
},
{
	"name": "Georgia",
	"capital": "Tbilisi",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Georgian"],
  "borders": ["ARM", "AZE", "RUS", "TUR"],
},
{
	"name": "Germany",
	"capital": "Berlin",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["German"],
	"borders": ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
},
{
	"name": "Ghana",
	"capital": "Accra",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
	"borders": ["BFA", "CIV", "TGO"],
},
{
	"name": "Gibraltar",
  "capital": "Gibraltar",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["English"],
  "borders": ["ESP"],
},
{
	"name": "Greece",
	"capital": "Athens",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Greek"],
	"borders": ["ALB", "BGR", "TUR", "MKD"],
},
{
	"name": "Grenada",
	"capital": "St. George's",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Guadeloupe",
  "capital": "Basse-Terre",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Guam",
  "capital": "Hag\u00e5t\u00f1a",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["English", "Chamorro"],
	"borders": [],
},
{
	"name": "Guatemala",
  "capital": "Guatemala City",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["BLZ", "SLV", "HND", "MEX"],
},
{
	"name": "Guinea",
	"capital": "Conakry",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["CIV", "GNB", "LBR", "MLI", "SEN", "SLE"],
},
{
	"name": "Guinea-Bissau",
	"capital": "Bissau",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["Portuguese"],
	"borders": ["GIN", "SEN"],
},
{
	"name": "Guyana",
  "capital": "Georgetown",
  "region": "Americas",
  "subregion": "South America",
  "language": ["English"],
  "borders": ["BRA", "SUR", "VEN"],
},
{
  "name": "Haiti",
	"capital": "Port-au-Prince",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French", "Haitian Creole"],
	"borders": ["DOM"],
},
{
	"name": "Vatican City",
  "capital": "Vatican City",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Italian"],
	"borders": ["ITA"],
},
{
	"name": "Honduras",
	"capital": "Tegucigalpa",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["GTM", "SLV", "NIC"],
},
{
	"name": "Hong Kong",
	"capital": "City of Victoria",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["English", "Chinese"],
	"borders": ["CHN"],
},
{
	"name": "Hungary",
	"capital": "Budapest",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Hungarian"],
	"borders": ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"],
},
{
	"name": "Iceland",
	"capital": "Reykjavik",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Icelandic"],
	"borders": [],
},
{
	"name": "India",
	"capital": "New Delhi",
	"region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Hindi", "English"],
	"borders": ["AFG", "BGD", "BTN", "MMR", "CHN", "NPL", "PAK", "LKA"],
},
{
	"name": "Indonesia",
  "capital": "Jakarta",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Indonesian"],
	"borders": ["TLS", "MYS", "PNG"],
},
{
	"name": "Ivory Coast",
	"capital": "Yamoussoukro",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["BFA", "GHA", "GIN", "LBR", "MLI"],
},
{
	"name": "Iran",
	"capital": "Tehran",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Persian"],
  "borders": ["AFG", "ARM", "AZE", "IRQ", "PAK", "TUR", "TKM"],
},
{
	"name": "Iraq",
	"capital": "Baghdad",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic", "Kurdish", "Syriac"],
	"borders": ["IRN", "JOR", "KWT", "SAU", "SYR", "TUR"],
},
{
	"name": "Ireland",
  "capital": "Dublin",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Irish", "English"],
  "borders": ["GBR"],
},
{
	"name": "Israel",
	"capital": "Jerusalem",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Hebrew", "Arabic"],
  "borders": ["EGY", "JOR", "LBN", "SYR"],
},
{
	"name": "Italy",
	"capital": "Rome",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Italian"],
	"borders": ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
},
{
	"name": "Jamaica",
	"capital": "Kingston",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Jamaican English"],
	"borders": [],
},
{
	"name": "Japan",
	"capital": "Tokyo",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Japanese"],
	"borders": [],
},
{
	"name": "Jordan",
  "capital": "Amman",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
	"borders": ["IRQ", "ISR", "SAU", "SYR"],
},
{
	"name": "Kazakhstan",
	"capital": "Astana",
	"region": "Asia",
	"subregion": "Central Asia",
	"language": ["Kazakh", "Russian"],
	"borders": ["CHN", "KGZ", "RUS", "TKM", "UZB"],
},
{
  "name": "Kenya",
  "capital": "Nairobi",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["Swahili", "English"],
  "borders": ["ETH", "SOM", "SSD", "TZA", "UGA"],
},
{
	"name": "Kiribati",
  "capital": "South Tarawa",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Gilbertese"],
	"borders": [],
},
{
	"name": "Kuwait",
  "capital": "Kuwait City",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["IRN", "SAU"],
},
{
  "name": "Kyrgyzstan",
  "capital": "Bishkek",
  "region": "Asia",
  "subregion": "Central Asia",
  "language": ["Kyrgyz", "Russian"],
  "borders": ["CHN", "KAZ", "TJK", "UZB"],
},
{
	"name": "Laos",
	"capital": "Vientiane",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Lao"],
  "borders": ["MMR", "KHM", "CHN", "THA", "VNM"],
},
{
  "name": "Latvia",
  "capital": "Riga",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Latvian"],
  "borders": ["BLR", "EST", "LTU", "RUS"],
},
{
	"name": "Lebanon",
	"capital": "Beirut",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic", "French"],
	"borders": ["ISR", "SYR"],
},
{
	"name": "Lesotho",
	"capital": "Maseru",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["Sesotho", "English"],
	"borders": ["ZAF"],
},
{
	"name": "Liberia",
	"capital": "Monrovia",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
  "borders": ["GIN", "CIV", "SLE"],
},
{
	"name": "Libya",
	"capital": "Tripoli",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic"],
  "borders": ["DZA", "TCD", "EGY", "NER", "SDN", "TUN"],
},
{
	"name": "Liechtenstein",
	"capital": "Vaduz",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["German"],
	"languageCodes": ["de"],
	"borders": ["AUT", "CHE"],
},
{
	"name": "Lithuania",
	"capital": "Vilnius",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Lithuanian"],
	"languageCodes": ["lt"],
	"borders": ["BLR", "LVA", "POL", "RUS"],
},
{
	"name": "Luxembourg",
  "capital": "Luxembourg",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["French", "German", "Luxembourgish"],
  "borders": ["BEL", "FRA", "DEU"],
},
{
	"name": "Macedonia",
	"capital": "Skopje",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Macedonian"],
	"borders": ["ALB", "BGR", "GRC", "KOS", "SRB"],
},
{
	"name": "Madagascar",
	"capital": "Antananarivo",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Malagasy", "French"],
	"borders": [],
},
{
	"name": "Malawi",
	"capital": "Lilongwe",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Chichewa", "English"],
	"languageCodes": ["en", "ny"],
	"borders": ["MOZ", "TZA", "ZMB"],
},
{
	"name": "Malaysia",
	"capital": "Kuala Lumpur",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Malaysian"],
	"borders": ["BRN", "IDN", "THA"],
},
{
	"name": "Maldives",
	"capital": "Mal\u00e9",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Maldivian"],
  "borders": [],
},
{
	"name": "Mali",
	"capital": "Bamako",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["DZA", "BFA", "GIN", "CIV", "MRT", "NER", "SEN"],
},
{
	"name": "Malta",
	"capital": "Valletta",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Maltese", "English"],
	"borders": [],
},
{
	"name": "Marshall Islands",
	"capital": "Majuro",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["Marshallese", "English"],
	"borders": [],
},
{
	"name": "Martinique",
	"capital": "Fort-de-France",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Mauritania",
  "capital": "Nouakchott",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["Arabic"],
  "borders": ["DZA", "MLI", "SEN", "ESH"],
},
{
	"name": "Mauritius",
	"capital": "Port Louis",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["French"],
	"borders": [],
},
{
  "name": "Mayotte",
  "capital": "Mamoudzou",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["French"],
  "borders": [],
},
{
	"name": "Mexico",
	"capital": "Mexico City",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["BLZ", "GTM", "USA"],
},
{
	"name": "Micronesia",
  "capital": "Palikir",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Moldova",
	"capital": "Chi\u0219in\u0103u",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Moldovan"],
  "borders": ["ROU", "UKR"],
},
{
  "name": "Monaco",
  "capital": "Monaco",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["French"],
  "borders": ["FRA"],
},
{
	"name": "Mongolia",
	"capital": "Ulan Bator",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Mongolian"],
	"borders": ["CHN", "RUS"],
},
{
	"name": "Montenegro",
	"capital": "Podgorica",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Montenegrin"],
	"borders": ["ALB", "BIH", "HRV", "KOS", "SRB"],
},
{
	"name": "Montserrat",
	"capital": "Plymouth",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Morocco",
	"capital": "Rabat",
	"region": "Africa",
  "subregion": "Northern Africa",
  "language": ["Arabic", "Berber"],
  "borders": ["DZA", "ESH", "ESP"],
},
{
	"name": "Mozambique",
  "capital": "Maputo",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["Portuguese"],
  "borders": ["MWI", "ZAF", "SWZ", "TZA", "ZMB", "ZWE"],
},
{
	"name": "Myanmar",
	"capital": "Naypyidaw",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Burmese"],
	"borders": ["BGD", "CHN", "IND", "LAO", "THA"],
},
{
	"name": "Namibia",
	"capital": "Windhoek",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["English"],
	"borders": ["AGO", "BWA", "ZAF", "ZMB"],
},
{
	"name": "Nauru",
	"capital": "Yaren",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["Nauruan", "English"],
  "borders": [],
},
{
	"name": "Nepal",
	"capital": "Kathmandu",
	"region": "Asia",
	"subregion": "Southern Asia",
	"language": ["Nepali"],
	"borders": ["CHN", "IND"],
},
{
	"name": "Netherlands",
	"capital": "Amsterdam",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["Dutch"],
	"borders": ["BEL", "DEU"],
},
{
  "name": "New Caledonia",
	"capital": "Noum\u00e9a",
  "region": "Oceania",
  "subregion": "Melanesia",
  "language": ["French"],
  "borders": [],
},
{
	"name": "New Zealand",
	"capital": "Wellington",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English", "M\u0101ori", "New Zealand Sign Language"],
	"borders": [],
},
{
	"name": "Nicaragua",
	"capital": "Managua",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["CRI", "HND"],
},
{
	"name": "Niger",
  "capital": "Niamey",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["DZA", "BEN", "BFA", "TCD", "LBY", "MLI", "NGA"],
},
{
	"name": "Nigeria",
  "capital": "Abuja",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["English"],
  "borders": ["BEN", "CMR", "TCD", "NER"],
},
{
	"name": "Niue",
	"capital": "Alofi",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Niuean", "English"],
	"borders": [],
},
{
	"name": "Norfolk Island",
	"capital": "Kingston",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English", "Norfuk"],
	"borders": [],
},
{
	"name": "North Korea",
	"capital": "Pyongyang",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Korean"],
	"borders": ["CHN", "KOR", "RUS"],
},
{
	"name": "Northern Mariana Islands",
	"capital": "Saipan",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Chamorro", "Carolinian"],
	"borders": [],
},
{
	"name": "Norway",
	"capital": "Oslo",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Norwegian", "Bokm\u00e5l", "Nynorsk"],
	"borders": ["FIN", "SWE", "RUS"],
},
{
	"name": "Oman",
	"capital": "Muscat",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic"],
	"borders": ["SAU", "ARE", "YEM"],
},
{
	"name": "Pakistan",
	"capital": "Islamabad",
	"region": "Asia",
	"subregion": "Southern Asia",
	"language": ["English", "Urdu"],
	"borders": ["AFG", "CHN", "IND", "IRN"],
},
{
  "name": "Palau",
	"capital": "Ngerulmud",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Palauan"],
	"borders": [],
},
{
	"name": "Palestine",
  "capital": "Ramallah",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["ISR", "EGY", "JOR"],
},
{
	"name": "Panama",
  "capital": "Panama City",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["Spanish"],
  "borders": ["COL", "CRI"],
},
{
	"name": "Papua New Guinea",
	"capital": "Port Moresby",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["Hiri Motu", "Tok Pisin", "English"],
	"borders": ["IDN"],
},
{
	"name": "Paraguay",
	"capital": "Asunci\u00f3n",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish", "Guaran\u00ed"],
	"borders": ["ARG", "BOL", "BRA"],
},
{
	"name": "Peru",
	"capital": "Lima",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish", "Quechua", "Aymara"],
	"borders": ["BOL", "BRA", "CHL", "COL", "ECU"],
},
{
	"name": "Philippines",
	"capital": "Manila",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Filipino", "English"],
	"borders": [],
},
{
	"name": "Pitcairn Islands",
	"capital": "Adamstown",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Poland",
	"capital": "Warsaw",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Polish"],
	"borders": ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
},
{
	"name": "Portugal",
	"capital": "Lisbon",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Portuguese"],
	"borders": ["ESP"],
},
{
	"name": "Puerto Rico",
	"capital": "San Juan",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Spanish", "English"],
	"borders": [],
},
{
	"name": "Qatar",
	"capital": "Doha",
	"region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["SAU"],
},
{
	"name": "Republic of Kosovo",
	"capital": "Pristina",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Albanian", "Serbian"],
	"borders": ["ALB", "MKD", "MNE", "SRB"],
},
{
	"name": "R\u00e9union",
	"capital": "Saint-Denis",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Romania",
  "capital": "Bucharest",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Romanian"],
  "borders": ["BGR", "HUN", "MDA", "SRB", "UKR"],
},
{
	"name": "Russia",
	"capital": "Moscow",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Russian"],
	"borders": ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"],
},
{
	"name": "Rwanda",
	"capital": "Kigali",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Kinyarwanda", "French", "English"],
	"borders": ["BDI", "COD", "TZA", "UGA"],
},
{
	"name": "Saint Barth\u00e9lemy",
	"capital": "Gustavia",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Saint Helena",
	"capital": "Jamestown",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Saint Kitts and Nevis",
	"capital": "Basseterre",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Saint Lucia",
	"capital": "Castries",
	"region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Saint Martin",
	"capital": "Marigot",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": ["SXM", "NLD"],
},
{
	"name": "Saint Pierre and Miquelon",
	"capital": "Saint-Pierre",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Saint Vincent and the Grenadines",
	"capital": "Kingstown",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Samoa",
	"capital": "Apia",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Samoan", "English"],
	"borders": [],
},
{
	"name": "San Marino",
	"capital": "City of San Marino",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Italian"],
	"borders": ["ITA"],
},
{
	"name": "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
	"capital": "S\u00e3o Tom\u00e9",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["Portuguese"],
	"borders": [],
},
{
	"name": "Saudi Arabia",
	"capital": "Riyadh",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic"],
	"borders": ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"],
},
{
  "name": "Senegal",
  "capital": "Dakar",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["French"],
  "borders": ["The Gambia", "GIN", "GNB", "MLI", "MRT"],
},
{
	"name": "Serbia",
	"capital": "Belgrade",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Serbian"],
	"borders": ["BIH", "BGR", "HRV", "HUN", "KOS", "MKD", "MNE", "ROU"],
},
{
	"name": "Seychelles",
	"capital": "Victoria",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["French", "English", "Seychellois Creole"],
	"borders": [],
},
{
	"name": "Sierra Leone",
	"capital": "Freetown",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
	"borders": ["GIN", "LBR"],
},
{
	"name": "Singapore",
	"capital": "Singapore",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["English", "Malay", "Mandarin", "Tamil"],
	"borders": [],
},
{
	"name": "Sint Maarten",
	"capital": "Philipsburg",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Dutch", "English"],
	"borders": ["MAF"],
},
{
	"name": "Slovakia",
  "capital": "Bratislava",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Slovak"],
  "borders": ["AUT", "CZE", "HUN", "POL", "UKR"],
},
{
	"name": "Slovenia",
	"capital": "Ljubljana",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Slovene"],
	"borders": ["AUT", "HRV", "ITA", "HUN"],
},
{
	"name": "Solomon Islands",
	"capital": "Honiara",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Somalia",
	"capital": "Mogadishu",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Somali", "Arabic"],
  "borders": ["DJI", "ETH", "KEN"],
},
{
	"name": "South Africa",
	"capital": "Pretoria",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["Afrikaans", "English", "Southern Ndebele", "Northern Sotho", "Southern Sotho", "Swazi", "Tsonga", "Tswana", "Venda", "Xhosa", "Zulu"],
	"borders": ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
},
{
	"name": "South Georgia",
	"capital": "King Edward Point",
	"region": "Americas",
	"subregion": "South America",
	"language": ["English"],
	"borders": [],
},
{
	"name": "South Korea",
	"capital": "Seoul",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Korean"],
	"borders": ["PRK"],
},
{
	"name": "South Sudan",
	"capital": "Juba",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["English"],
	"borders": ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"],
},
{
	"name": "Spain",
	"capital": "Madrid",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Spanish", "Basque", "Catalan", "Galician", "Occitan"],
	"borders": ["AND", "FRA", "GIB", "PRT", "MAR"],
},
{
	"name": "Sri Lanka",
	"capital": "Colombo",
	"region": "Asia",
	"subregion": "Southern Asia",
	"language": ["Sinhala", "Tamil"],
	"borders": ["IND"],
},
{
	"name": "Sudan",
	"capital": "Khartoum",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic", "English"],
	"borders": ["CAF", "TCD", "EGY", "ERI", "ETH", "LBY", "SSD"],
},
{
	"name": "Suriname",
	"capital": "Paramaribo",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Dutch"],
	"borders": ["BRA", "GUF", "FRA", "GUY"],
},
{
	"name": "Swaziland",
	"capital": "Lobamba",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["Swazi", "English"],
	"borders": ["MOZ", "ZAF"],
},
{
	"name": "Sweden",
	"capital": "Stockholm",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Swedish"],
	"borders": ["FIN", "NOR"],
},
{
	"name": "Switzerland",
	"capital": "Bern",
	"region": "Europe",
  "subregion": "Western Europe",
  "language": ["German", "French", "Italian", "Romansh"],
  "borders": ["AUT", "FRA", "ITA", "LIE", "DEU"],
},
{
	"name": "Syria",
  "capital": "Damascus",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["IRQ", "ISR", "JOR", "LBN", "TUR"],
},
{
	"name": "Taiwan",
	"capital": "Taipei",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Standard Chinese"],
	"borders": [],
},
{
	"name": "Tajikistan",
	"capital": "Dushanbe",
	"region": "Asia",
	"subregion": "Central Asia",
	"language": ["Tajik"],
	"borders": ["AFG", "CHN", "KGZ", "UZB"],
},
{
	"name": "Tanzania",
	"capital": "Dodoma",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Swahili", "English"],
  "borders": ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"],
},
{
	"name": "Thailand",
	"capital": "Bangkok",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Thai"],
	"borders": ["Burma", "KHM", "LAO", "MYS"],
},
{
	"name": "Timor-Leste",
	"capital": "Dili",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Portuguese", "Tetum"],
	"borders": ["IDN"],
},
{
	"name": "Togo",
	"capital": "Lom\u00e9",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["BEN", "BFA", "GHA"],
},
{
  "name": "Tokelau",
	"capital": "Fakaofo",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["Tokelauan", "English", "Samoan"],
  "borders": [],
},
{
	"name": "Tonga",
  "capital": "Nuku'alofa",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["Tongan", "English"],
  "borders": [],
},
{
	"name": "Trinidad and Tobago",
	"capital": "Port of Spain",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Tunisia",
	"capital": "Tunis",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic"],
	"borders": ["DZA", "LBY"],
},
{
	"name": "Turkey",
	"capital": "Ankara",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Turkish"],
	"borders": ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
},
{
	"name": "Turkmenistan",
	"capital": "Ashgabat",
	"region": "Asia",
	"subregion": "Central Asia",
	"language": ["Turkmen"],
  "borders": ["AFG", "IRN", "KAZ", "UZB"],
},
{
	"name": "Turks and Caicos Islands",
	"capital": "Cockburn Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Tuvalu",
	"capital": "Funafuti",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Tuvaluan", "English"],
	"borders": [],
},
{
	"name": "Uganda",
	"capital": "Kampala",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["English", "Swahili"],
	"borders": ["COD", "KEN", "RWA", "SSD", "TZA"],
},
{
	"name": "Ukraine",
	"capital": "Kiev",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Ukrainian"],
	"borders": ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
},
{
  "name": "United Arab Emirates",
  "capital": "Abu Dhabi",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["OMN", "SAU"],
},
{
	"name": "United Kingdom",
	"capital": "London",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["English"],
	"borders": ["IRL"],
},
{
	"name": "United States",
	"capital": "Washington D.C.",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["English"],
	"borders": ["CAN", "MEX"],
},
{
	"name": "United States Virgin Islands",
	"capital": "Charlotte Amalie",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Uruguay",
	"capital": "Montevideo",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["ARG", "BRA"],
},
{
	"name": "Uzbekistan",
  "capital": "Tashkent",
  "region": "Asia",
  "subregion": "Central Asia",
  "language": ["Uzbek"],
  "borders": ["AFG", "KAZ", "KGZ", "TJK", "TKM"],
},
{
	"name": "Vanuatu",
	"capital": "Port Vila",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["Bislama", "French", "English"],
	"borders": [],
},
{
	"name": "Venezuela",
	"capital": "Caracas",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["BRA", "COL", "GUY"],
},
{
	"name": "Vietnam",
	"capital": "Hanoi",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Vietnamese"],
	"borders": ["KHM", "CHN", "LAO"],
},
{
	"name": "Wallis and Futuna",
	"capital": "Mata-Utu",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Western Sahara",
	"capital": "El Aai\u00fan",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Berber", "Hassaniya", "Spanish"],
	"borders": ["DZA", "MRT", "MAR"],
},
{
	"name": "Yemen",
	"capital": "Sana'a",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic"],
	"borders": ["OMN", "SAU"],
},
{
	"name": "Zambia",
	"capital": "Lusaka",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["English"],
	"borders": ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"],
},
{
	"name": "Zimbabwe",
	"capital": "Harare",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Chewa", "Chibarwe", "English", "Kalanga", "Koisan", "Nambya", "Ndau", "Ndebele", "Shangani", "Shona", "Zimbabwean sign language", "Sotho", "Tonga", "Tswana", "Venda", "Xhosa"],
	"borders": ["BWA", "MOZ", "ZAF", "ZMB"],
}

]
