const COUNTRIES_ASIA = [

{
  "name":"Afghanistan",
  "capital": "Kabul",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Pashto", "Dari"],
  "borders": ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
  "flag": "flags/af.svg",
},
{
  "name": "Armenia",
  "nativeName": "\u0540\u0561\u0575\u0561\u057d\u057f\u0561\u0576",
  "capital": "Yerevan",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Armenian"],
  "borders": ["AZE", "GEO", "IRN", "TUR"],
  "flag": "flags/am.svg",
},
{
  "name": "Azerbaijan",
  "capital": "Baku",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Azerbaijani"],
  "borders": ["ARM", "GEO", "IRN", "RUS", "TUR"],
  "flag": "flags/az.svg",
},
{
  "name": "Bahrain",
  "capital": "Manama",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": [],
  "flag": "flags/bh.svg",
},
{
  "name": "Bangladesh",
  "capital": "Dhaka",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Bangla"],
  "borders": ["MMR", "IND"],
  "flag": "flags/bd.svg",
},
{
  "name": "Bhutan",
  "capital": "Thimphu",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Dzongkha"],
  "borders": ["CHN", "IND"],
  "flag": "flags/bt.svg",
},
{
	"name": "Brunei",
	"capital": "Bandar Seri Begawan",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Malay"],
	"borders": ["MYS"],
  "flag": "flags/bn.svg",
},
{
  "name": "Cambodia",
  "capital": "Phnom Penh",
  "region": "Asia",
  "subregion": "South-Eastern Asia",
  "language": ["Khmer"],
  "borders": ["LAO", "THA", "VNM"],
  "flag": "flags/kh.svg",
},
{
	"name": "China",
  "capital": "Beijing",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Standard Chinese"],
	"borders": ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "PAK", "RUS", "TJK", "VNM"],
  "flag": "flags/ch.svg",
},
{
	"name": "Georgia",
	"capital": "Tbilisi",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Georgian"],
  "borders": ["ARM", "AZE", "RUS", "TUR"],
  "flag": "flags/ge.svg",
},
{
	"name": "Hong Kong",
	"capital": "City of Victoria",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["English", "Chinese"],
	"borders": ["CHN"],
  "flag": "flags/hk.svg",
},
{
	"name": "India",
	"capital": "New Delhi",
	"region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Hindi", "English"],
	"borders": ["AFG", "BGD", "BTN", "MMR", "CHN", "NPL", "PAK", "LKA"],
  "flag": "flags/in.svg",
},
{
	"name": "Indonesia",
  "capital": "Jakarta",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Indonesian"],
	"borders": ["TLS", "MYS", "PNG"],
  "flag": "flags/id.svg",
},
{
	"name": "Iran",
	"capital": "Tehran",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Persian"],
  "borders": ["AFG", "ARM", "AZE", "IRQ", "PAK", "TUR", "TKM"],
  "flag": "flags/ir.svg",
},
{
	"name": "Iraq",
	"capital": "Baghdad",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic", "Kurdish", "Syriac"],
	"borders": ["IRN", "JOR", "KWT", "SAU", "SYR", "TUR"],
  "flag": "flags/iq.svg",
},
{
	"name": "Israel",
	"capital": "Jerusalem",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Hebrew", "Arabic"],
  "borders": ["EGY", "JOR", "LBN", "SYR"],
  "flag": "flags/il.svg",
},
{
	"name": "Japan",
	"capital": "Tokyo",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Japanese"],
	"borders": [],
  "flag": "flags/jp.svg",
},
{
	"name": "Jordan",
  "capital": "Amman",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
	"borders": ["IRQ", "ISR", "SAU", "SYR"],
  "flag": "flags/jo.svg",
},
{
	"name": "Kazakhstan",
	"capital": "Astana",
	"region": "Asia",
	"subregion": "Central Asia",
	"language": ["Kazakh", "Russian"],
	"borders": ["CHN", "KGZ", "RUS", "TKM", "UZB"],
  "flag": "flags/kz.svg",
},
{
	"name": "Kuwait",
  "capital": "Kuwait City",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["IRN", "SAU"],
  "flag": "flags/kw.svg",
},
{
  "name": "Kyrgyzstan",
  "capital": "Bishkek",
  "region": "Asia",
  "subregion": "Central Asia",
  "language": ["Kyrgyz", "Russian"],
  "borders": ["CHN", "KAZ", "TJK", "UZB"],
  "flag": "flags/kg.svg",
},
{
	"name": "Laos",
	"capital": "Vientiane",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Lao"],
  "borders": ["MMR", "KHM", "CHN", "THA", "VNM"],
  "flag": "flags/la.svg",
},
{
	"name": "Lebanon",
	"capital": "Beirut",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic", "French"],
	"borders": ["ISR", "SYR"],
  "flag": "flags/lb.svg",
},
{
	"name": "Malaysia",
	"capital": "Kuala Lumpur",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Malaysian"],
	"borders": ["BRN", "IDN", "THA"],
  "flag": "flags/my.svg",
},
{
	"name": "Maldives",
	"capital": "Mal\u00e9",
  "region": "Asia",
  "subregion": "Southern Asia",
  "language": ["Maldivian"],
  "borders": [],
  "flag": "flags/mv.svg",
},
{
	"name": "Mongolia",
	"capital": "Ulan Bator",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Mongolian"],
	"borders": ["CHN", "RUS"],
  "flag": "flags/mn.svg",
},
{
	"name": "Myanmar",
	"capital": "Naypyidaw",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Burmese"],
	"borders": ["BGD", "CHN", "IND", "LAO", "THA"],
  "flag": "flags/mm.svg",
},
{
	"name": "Nepal",
	"capital": "Kathmandu",
	"region": "Asia",
	"subregion": "Southern Asia",
	"language": ["Nepali"],
	"borders": ["CHN", "IND"],
  "flag": "flags/np.svg",
},
{
	"name": "North Korea",
	"capital": "Pyongyang",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Korean"],
	"borders": ["CHN", "KOR", "RUS"],
  "flag": "flags/kp.svg",
},
{
	"name": "Oman",
	"capital": "Muscat",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic"],
	"borders": ["SAU", "ARE", "YEM"],
  "flag": "flags/om.svg",
},
{
	"name": "Pakistan",
	"capital": "Islamabad",
	"region": "Asia",
	"subregion": "Southern Asia",
	"language": ["English", "Urdu"],
	"borders": ["AFG", "CHN", "IND", "IRN"],
  "flag": "flags/pk.svg",
},
{
	"name": "Palestine",
  "capital": "Ramallah",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["ISR", "EGY", "JOR"],
  "flag": "flags/ps.svg",
},
{
	"name": "Philippines",
	"capital": "Manila",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Filipino", "English"],
	"borders": [],
  "flag": "flags/ph.svg",
},
{
	"name": "Qatar",
	"capital": "Doha",
	"region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["SAU"],
  "flag": "flags/qa.svg",
},
{
	"name": "Saudi Arabia",
	"capital": "Riyadh",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic"],
	"borders": ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"],
  "flag": "flags/sa.svg",
},
{
	"name": "Singapore",
	"capital": "Singapore",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["English", "Malay", "Mandarin", "Tamil"],
	"borders": [],
  "flag": "flags/sg.svg",
},
{
	"name": "South Korea",
	"capital": "Seoul",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Korean"],
	"borders": ["PRK"],
  "flag": "flags/kr.svg",
},
{
	"name": "Sri Lanka",
	"capital": "Colombo",
	"region": "Asia",
	"subregion": "Southern Asia",
	"language": ["Sinhala", "Tamil"],
	"borders": ["IND"],
  "flag": "flags/lk.svg",
},
{
	"name": "Syria",
  "capital": "Damascus",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["IRQ", "ISR", "JOR", "LBN", "TUR"],
  "flag": "flags/sy.svg",
},
{
	"name": "Taiwan",
	"capital": "Taipei",
	"region": "Asia",
	"subregion": "Eastern Asia",
	"language": ["Standard Chinese"],
	"borders": [],
  "flag": "flags/tw.svg",
},
{
	"name": "Tajikistan",
	"capital": "Dushanbe",
	"region": "Asia",
	"subregion": "Central Asia",
	"language": ["Tajik"],
	"borders": ["AFG", "CHN", "KGZ", "UZB"],
  "flag": "flags/tj.svg",
},
{
	"name": "Thailand",
	"capital": "Bangkok",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Thai"],
	"borders": ["Burma", "KHM", "LAO", "MYS"],
  "flag": "flags/th.svg",
},
{
	"name": "Timor-Leste",
	"capital": "Dili",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Portuguese", "Tetum"],
	"borders": ["IDN"],
  "flag": "flags/tl.svg",
},
{
	"name": "Turkey",
	"capital": "Ankara",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Turkish"],
	"borders": ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
  "flag": "flags/tr.svg",
},
{
	"name": "Turkmenistan",
	"capital": "Ashgabat",
	"region": "Asia",
	"subregion": "Central Asia",
	"language": ["Turkmen"],
  "borders": ["AFG", "IRN", "KAZ", "UZB"],
  "flag": "flags/tm.svg",
},
{
  "name": "United Arab Emirates",
  "capital": "Abu Dhabi",
  "region": "Asia",
  "subregion": "Western Asia",
  "language": ["Arabic"],
  "borders": ["OMN", "SAU"],
  "flag": "flags/ae.svg",
},
{
	"name": "Uzbekistan",
  "capital": "Tashkent",
  "region": "Asia",
  "subregion": "Central Asia",
  "language": ["Uzbek"],
  "borders": ["AFG", "KAZ", "KGZ", "TJK", "TKM"],
  "flag": "flags/uz.svg",
},
{
	"name": "Vietnam",
	"capital": "Hanoi",
	"region": "Asia",
	"subregion": "South-Eastern Asia",
	"language": ["Vietnamese"],
	"borders": ["KHM", "CHN", "LAO"],
  "flag": "flags/vn.svg",
},
{
	"name": "Yemen",
	"capital": "Sana'a",
	"region": "Asia",
	"subregion": "Western Asia",
	"language": ["Arabic"],
	"borders": ["OMN", "SAU"],
  "flag": "flags/ye.svg",
}

]
