const COUNTRIES_AFRICA = [

{
  "name": "Algeria",
  "capital": "Algiers",
  "region": "Africa",
  "subregion": "Northern Africa",
  "language": ["Arabic"],
  "borders": ["TUN", "LDY", "NER", "ESH", "MRT", "MLI", "MAR"],
},
{
  "name": "Angola",
  "capital": "Luanda",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["Portuguese"],
  "borders": ["COG", "COD", "ZMB", "NAM"],
},
{
  "name": "Benin",
  "capital": "Porto-Novo",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["French"],
  "borders": ["BFA", "NER", "NGA", "TGO"],
},
{
  "name": "Botswana",
  "capital": "Gaborone",
  "region": "Africa",
  "subregion": "Southern Africa",
  "language": ["English", "Setswana"],
  "borders": ["NAM", "ZAF", "ZMB", "ZWE"],
},
{
  "name": "British Indian Ocean Territory",
  "capital": "Diego Garcia",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Burkina Faso",
  "capital": "Ouagadougou",
	"region": "Africa",
  "subregion": "Western Africa",
	"language": ["French"],
	"borders": ["BEN", "CIV", "GHA", "MLI", "NER", "TGO"],
},
{
	"name": "Burundi",
	"capital": "Bujumbura",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Kirundi", "French"],
	"borders": ["COD", "RWA", "TZA"],
},
{
  "name": "Cameroon",
  "capital": "Yaound\u00e9",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["French", "English"],
  "borders": ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"],
},
{
	"name": "Cape Verde",
	"capital": "Praia",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["Portuguese"],
	"borders": [],
},
{
	"name": "Central African Republic",
	"capital": "Bangui",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["Sango", "French"],
	"borders": ["CMR", "TCD", "COD", "COG", "SSD", "SDN"],
},
{
	"name": "Chad",
	"capital": "N'Djamena",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["French", "Arabic"],
	"borders": ["CMR", "CAF", "LBY", "NER", "NGA", "SSD"],
},
{
	"name": "Comoros",
	"capital": "Moroni",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Comorian", "Arabic", "French"],
	"borders": [],
},
{
	"name": "Republic of the Congo",
	"capital": "Brazzaville",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["French"],
  "borders": ["AGO", "CMR", "CAF", "COD", "GAB"],
},
{
	"name": "Democratic Republic of the Congo",
	"capital": "Kinshasa",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["French"],
	"borders": ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"],
},
{
	"name": "Djibouti",
	"capital": "Djibouti",
	"region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["French", "Arabic"],
	"borders": ["ERI", "ETH", "SOM"],
},
{
	"name": "Egypt",
	"capital": "Cairo",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic"],
	"borders": ["ISR", "LBY", "SDN"],
},
{
  "name": "Equatorial Guinea",
  "capital": "Malabo",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["Spanish", "French", "Portuguese"],
	"borders": ["CMR", "GAB"],
},
{
	"name": "Eritrea",
	"capital": "Asmara",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Tigrinya", "Arabic", "English"],
	"borders": ["DJI", "ETH", "SDN"],
},
{
	"name": "Ethiopia",
  "capital": "Addis Ababa",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["Amharic"],
  "borders": ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"],
},
{
  "name": "Gabon",
  "capital": "Libreville",
  "region": "Africa",
  "subregion": "Middle Africa",
  "language": ["French"],
	"borders": ["CMR", "COG", "GNQ"],
},
{
  "name": "Gambia",
  "capital": "Banjul",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["English"],
  "borders": ["SEN"],
},
{
	"name": "Ghana",
	"capital": "Accra",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
	"borders": ["BFA", "CIV", "TGO"],
},
{
	"name": "Guinea",
	"capital": "Conakry",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["CIV", "GNB", "LBR", "MLI", "SEN", "SLE"],
},
{
	"name": "Guinea-Bissau",
	"capital": "Bissau",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["Portuguese"],
	"borders": ["GIN", "SEN"],
},
{
	"name": "Ivory Coast",
	"capital": "Yamoussoukro",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["BFA", "GHA", "GIN", "LBR", "MLI"],
},
{
  "name": "Kenya",
  "capital": "Nairobi",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["Swahili", "English"],
  "borders": ["ETH", "SOM", "SSD", "TZA", "UGA"],
},
{
	"name": "Lesotho",
	"capital": "Maseru",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["Sesotho", "English"],
	"borders": ["ZAF"],
},
{
	"name": "Liberia",
	"capital": "Monrovia",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
  "borders": ["GIN", "CIV", "SLE"],
},
{
	"name": "Libya",
	"capital": "Tripoli",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic"],
  "borders": ["DZA", "TCD", "EGY", "NER", "SDN", "TUN"],
},
{
	"name": "Madagascar",
	"capital": "Antananarivo",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Malagasy", "French"],
	"borders": [],
},
{
	"name": "Malawi",
	"capital": "Lilongwe",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Chichewa", "English"],
	"languageCodes": ["en", "ny"],
	"borders": ["MOZ", "TZA", "ZMB"],
},
{
	"name": "Mali",
	"capital": "Bamako",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["DZA", "BFA", "GIN", "CIV", "MRT", "NER", "SEN"],
},
{
	"name": "Mauritania",
  "capital": "Nouakchott",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["Arabic"],
  "borders": ["DZA", "MLI", "SEN", "ESH"],
},
{
	"name": "Mauritius",
	"capital": "Port Louis",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["French"],
	"borders": [],
},
{
  "name": "Mayotte",
  "capital": "Mamoudzou",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["French"],
  "borders": [],
},
{
	"name": "Morocco",
	"capital": "Rabat",
	"region": "Africa",
  "subregion": "Northern Africa",
  "language": ["Arabic", "Berber"],
  "borders": ["DZA", "ESH", "ESP"],
},
{
	"name": "Mozambique",
  "capital": "Maputo",
  "region": "Africa",
  "subregion": "Eastern Africa",
  "language": ["Portuguese"],
  "borders": ["MWI", "ZAF", "SWZ", "TZA", "ZMB", "ZWE"],
},
{
	"name": "Namibia",
	"capital": "Windhoek",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["English"],
	"borders": ["AGO", "BWA", "ZAF", "ZMB"],
},
{
	"name": "Niger",
  "capital": "Niamey",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["DZA", "BEN", "BFA", "TCD", "LBY", "MLI", "NGA"],
},
{
	"name": "Nigeria",
  "capital": "Abuja",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["English"],
  "borders": ["BEN", "CMR", "TCD", "NER"],
},
{
	"name": "R\u00e9union",
	"capital": "Saint-Denis",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Rwanda",
	"capital": "Kigali",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Kinyarwanda", "French", "English"],
	"borders": ["BDI", "COD", "TZA", "UGA"],
},
{
	"name": "Saint Helena",
	"capital": "Jamestown",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
	"borders": [],
},
{
	"name": "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
	"capital": "S\u00e3o Tom\u00e9",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["Portuguese"],
	"borders": [],
},
{
  "name": "Senegal",
  "capital": "Dakar",
  "region": "Africa",
  "subregion": "Western Africa",
  "language": ["French"],
  "borders": ["The Gambia", "GIN", "GNB", "MLI", "MRT"],
},
{
	"name": "Seychelles",
	"capital": "Victoria",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["French", "English", "Seychellois Creole"],
	"borders": [],
},
{
	"name": "Sierra Leone",
	"capital": "Freetown",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["English"],
	"borders": ["GIN", "LBR"],
},
{
	"name": "Somalia",
	"capital": "Mogadishu",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Somali", "Arabic"],
  "borders": ["DJI", "ETH", "KEN"],
},
{
	"name": "South Africa",
	"capital": "Pretoria",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["Afrikaans", "English", "Southern Ndebele", "Northern Sotho", "Southern Sotho", "Swazi", "Tsonga", "Tswana", "Venda", "Xhosa", "Zulu"],
	"borders": ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
},
{
	"name": "South Sudan",
	"capital": "Juba",
	"region": "Africa",
	"subregion": "Middle Africa",
	"language": ["English"],
	"borders": ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"],
},
{
	"name": "Sudan",
	"capital": "Khartoum",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic", "English"],
	"borders": ["CAF", "TCD", "EGY", "ERI", "ETH", "LBY", "SSD"],
},
{
	"name": "Swaziland",
	"capital": "Lobamba",
	"region": "Africa",
	"subregion": "Southern Africa",
	"language": ["Swazi", "English"],
	"borders": ["MOZ", "ZAF"],
},
{
	"name": "Tanzania",
	"capital": "Dodoma",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Swahili", "English"],
  "borders": ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"],
},
{
	"name": "Togo",
	"capital": "Lom\u00e9",
	"region": "Africa",
	"subregion": "Western Africa",
	"language": ["French"],
	"borders": ["BEN", "BFA", "GHA"],
},
{
	"name": "Tunisia",
	"capital": "Tunis",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Arabic"],
	"borders": ["DZA", "LBY"],
},
{
	"name": "Uganda",
	"capital": "Kampala",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["English", "Swahili"],
	"borders": ["COD", "KEN", "RWA", "SSD", "TZA"],
},
{
	"name": "Western Sahara",
	"capital": "El Aai\u00fan",
	"region": "Africa",
	"subregion": "Northern Africa",
	"language": ["Berber", "Hassaniya", "Spanish"],
	"borders": ["DZA", "MRT", "MAR"],
},
{
	"name": "Zambia",
	"capital": "Lusaka",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["English"],
	"borders": ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"],
},
{
	"name": "Zimbabwe",
	"capital": "Harare",
	"region": "Africa",
	"subregion": "Eastern Africa",
	"language": ["Chewa", "Chibarwe", "English", "Kalanga", "Koisan", "Nambya", "Ndau", "Ndebele", "Shangani", "Shona", "Zimbabwean sign language", "Sotho", "Tonga", "Tswana", "Venda", "Xhosa"],
	"borders": ["BWA", "MOZ", "ZAF", "ZMB"],
}

]
