const COUNTRIES_OCEANIA = [

{
  "name": "American Samoa",
  "capital": "Pago Pago",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["English", "Samoan"],
  "borders": [],
  "flag": "flags/as.svg",
},
{
  "name": "Australia",
  "capital": "Canberra",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "language": ["English"],
  "borders": [],
  "flag": "flags/au.svg",
},
{
	"name": "Christmas Island",
	"capital": "Flying Fish Cove",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "language": ["English"],
  "borders": [],
  "flag": "flags/cx.svg",
},
{
	"name": "Cocos (Keeling) Islands",
	"capital": "West Island",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English"],
	"borders": [],
  "flag": "flags/cc.svg",
},
{
  "name": "Cook Islands",
	"capital": "Avarua",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["English", "Cook Islands M\u0101ori"],
	"borders": [],
  "flag": "flags/ck.svg",
},
{
	"name": "Fiji",
  "capital": "Suva",
  "region": "Oceania",
  "subregion": "Melanesia",
  "language": ["English", "Fijian", "Fiji Hindi"],
	"borders": [],
  "flag": "flags/fj.svg",
},
{
	"name": "French Polynesia",
	"capital": "Papeet\u0113",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["French"],
	"borders": [],
  "flag": "flags/pf.svg",
},
{
	"name": "Guam",
  "capital": "Hag\u00e5t\u00f1a",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["English", "Chamorro"],
	"borders": [],
  "flag": "flags/gu.svg",
},
{
	"name": "Kiribati",
  "capital": "South Tarawa",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Gilbertese"],
	"borders": [],
  "flag": "flags/ki.svg",
},
{
	"name": "Marshall Islands",
	"capital": "Majuro",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["Marshallese", "English"],
	"borders": [],
  "flag": "flags/mh.svg",
},
{
	"name": "Micronesia",
  "capital": "Palikir",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["English"],
  "borders": [],
  "flag": "flags/fm.svg",
},
{
	"name": "Nauru",
	"capital": "Yaren",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["Nauruan", "English"],
  "borders": [],
  "flag": "flags/nr.svg",
},
{
	"name": "New Zealand",
	"capital": "Wellington",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English", "M\u0101ori", "New Zealand Sign Language"],
	"borders": [],
  "flag": "flags/nz.svg",
},
{
	"name": "Niue",
	"capital": "Alofi",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Niuean", "English"],
	"borders": [],
  "flag": "flags/nu.svg",
},
{
	"name": "Norfolk Island",
	"capital": "Kingston",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English", "Norfuk"],
	"borders": [],
  "flag": "flags/nf.svg",
},
{
	"name": "Northern Mariana Islands",
	"capital": "Saipan",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Chamorro", "Carolinian"],
	"borders": [],
  "flag": "flags/mp.svg",
},
{
  "name": "Palau",
	"capital": "Ngerulmud",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Palauan"],
	"borders": [],
  "flag": "flags/pw.svg",
},
{
	"name": "Papua New Guinea",
	"capital": "Port Moresby",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["Hiri Motu", "Tok Pisin", "English"],
	"borders": ["IDN"],
  "flag": "flags/pg.svg",
},
{
	"name": "Samoa",
	"capital": "Apia",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Samoan", "English"],
	"borders": [],
  "flag": "flags/ws.svg",
},
{
	"name": "Solomon Islands",
	"capital": "Honiara",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["English"],
	"borders": [],
  "flag": "flags/sb.svg",
},
{
  "name": "Tokelau",
	"capital": "Fakaofo",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["Tokelauan", "English", "Samoan"],
  "borders": [],
  "flag": "flags/tk.svg",
},
{
	"name": "Tonga",
  "capital": "Nuku'alofa",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["Tongan", "English"],
  "borders": [],
  "flag": "flags/to.svg",
},
{
	"name": "Tuvalu",
	"capital": "Funafuti",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Tuvaluan", "English"],
	"borders": [],
  "flag": "flags/tv.svg",
},
{
	"name": "Vanuatu",
	"capital": "Port Vila",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["Bislama", "French", "English"],
	"borders": [],
  "flag": "flags/vu.svg",
},

]
