const COUNTRIES_EUROPE = [

{
  "name": "Albania",
  "capital": "Tirana",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Albanian"],
  "borders": ["MNE", "GRC", "MKD", "KOS"],
  "flag": "flags/al.svg",
},
{
  "name": "Andorra",
  "capital": "Andorra la Vella",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Catalan"],
  "borders": ["FRA", "ESP"],
  "flag": "flags/ad.svg",
},
{
  "name": "Austria",
  "capital": "Vienna",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["German"],
  "borders": ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
  "flag": "flags/at.svg",
},
{
  "name": "Belarus",
  "capital": "Minsk",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Belarusian", "Russian"],
  "borders": ["LVA", "LTU", "POL", "RUS", "UKR"],
  "flag": "flags/by.svg",
},
{
  "name": "Belgium",
  "capital": "Brussels",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["Dutch", "French", "German"],
  "borders": ["FRA", "DEU", "LUX", "NLD"],
  "flag": "flags/be.svg",
},
{
  "name": "Bosnia and Herzegovina",
  "capital": "Sarajevo",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Bosnian", "Croatian", "Serbian"],
  "borders": ["HRV", "MNE", "SRB"],
  "flag": "flags/ba.svg",
},
{
	"name": "Bulgaria",
	"capital": "Sofia",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Bulgarian"],
	"borders": ["GRC", "MKD", "ROU", "SRB", "TUR"],
  "flag": "flags/bg.svg",
},
{
	"name": "Croatia",
  "capital": "Zagreb",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Croatian"],
	"borders": ["BIH", "HUN", "MNE", "SRB", "SVN"],
  "flag": "flags/hr.svg",
},
{
	"name": "Cyprus",
	"capital": "Nicosia",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Greek", "Turkish"],
	"borders": ["GBR"],
  "flag": "flags/cy.svg",
},
{
	"name": "Czech Republic",
  "capital": "Prague",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Czech"],
  "borders": ["AUT", "DEU", "POL", "SVK"],
  "flag": "flags/cz.svg",
},
{
	"name": "Denmark",
	"capital": "Copenhagen",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Danish"],
	"borders": ["DEU"],
  "flag": "flags/dk.svg",
},
{
	"name": "Estonia",
  "capital": "Tallinn",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Estonian"],
  "borders": ["LVA", "RUS"],
  "flag": "flags/ee.svg",
},
{
	"name": "Finland",
  "capital": "Helsinki",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Finnish", "Swedish"],
  "borders": ["NOR", "SWE", "RUS"],
  "flag": "flags/fi.svg",
},
{
	"name": "France",
	"capital": "Paris",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["French"],
	"borders": ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
  "flag": "flags/fr.svg",
},
{
	"name": "Germany",
	"capital": "Berlin",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["German"],
	"borders": ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
  "flag": "flags/de.svg",
},
{
	"name": "Gibraltar",
  "capital": "Gibraltar",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["English"],
  "borders": ["ESP"],
  "flag": "flags/gi.svg",
},
{
	"name": "Greece",
	"capital": "Athens",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Greek"],
	"borders": ["ALB", "BGR", "TUR", "MKD"],
  "flag": "flags/gr.svg",
},
{
	"name": "Vatican City",
  "capital": "Vatican City",
  "region": "Europe",
  "subregion": "Southern Europe",
  "language": ["Italian"],
	"borders": ["ITA"],
  "flag": "flags/va.svg",
},
{
	"name": "Hungary",
	"capital": "Budapest",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Hungarian"],
	"borders": ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"],
  "flag": "flags/hu.svg",
},
{
	"name": "Iceland",
	"capital": "Reykjavik",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Icelandic"],
	"borders": [],
  "flag": "flags/is.svg",
},
{
	"name": "Ireland",
  "capital": "Dublin",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Irish", "English"],
  "borders": ["GBR"],
  "flag": "flags/ie.svg",
},
{
	"name": "Italy",
	"capital": "Rome",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Italian"],
	"borders": ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
  "flag": "flags/it.svg",
},
{
  "name": "Latvia",
  "capital": "Riga",
  "region": "Europe",
  "subregion": "Northern Europe",
  "language": ["Latvian"],
  "borders": ["BLR", "EST", "LTU", "RUS"],
  "flag": "flags/lv.svg",
},
{
	"name": "Liechtenstein",
	"capital": "Vaduz",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["German"],
	"languageCodes": ["de"],
	"borders": ["AUT", "CHE"],
  "flag": "flags/li.svg",
},
{
	"name": "Lithuania",
	"capital": "Vilnius",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Lithuanian"],
	"languageCodes": ["lt"],
	"borders": ["BLR", "LVA", "POL", "RUS"],
  "flag": "flags/lt.svg",
},
{
	"name": "Luxembourg",
  "capital": "Luxembourg",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["French", "German", "Luxembourgish"],
  "borders": ["BEL", "FRA", "DEU"],
  "flag": "flags/lu.svg",
},
{
	"name": "Macedonia",
	"capital": "Skopje",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Macedonian"],
	"borders": ["ALB", "BGR", "GRC", "KOS", "SRB"],
  "flag": "flags/mk.svg",
},
{
	"name": "Malta",
	"capital": "Valletta",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Maltese", "English"],
	"borders": [],
  "flag": "flags/mt.svg",
},
{
	"name": "Moldova",
	"capital": "Chi\u0219in\u0103u",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Moldovan"],
  "borders": ["ROU", "UKR"],
  "flag": "flags/md.svg",
},
{
  "name": "Monaco",
  "capital": "Monaco",
  "region": "Europe",
  "subregion": "Western Europe",
  "language": ["French"],
  "borders": ["FRA"],
  "flag": "flags/mc.svg",
},
{
	"name": "Montenegro",
	"capital": "Podgorica",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Montenegrin"],
	"borders": ["ALB", "BIH", "HRV", "KOS", "SRB"],
  "flag": "flags/me.svg",
},
{
	"name": "Netherlands",
	"capital": "Amsterdam",
	"region": "Europe",
	"subregion": "Western Europe",
	"language": ["Dutch"],
	"borders": ["BEL", "DEU"],
  "flag": "flags/nl.svg",
},
{
	"name": "Norway",
	"capital": "Oslo",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Norwegian", "Bokm\u00e5l", "Nynorsk"],
	"borders": ["FIN", "SWE", "RUS"],
  "flag": "flags/no.svg",
},
{
	"name": "Poland",
	"capital": "Warsaw",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Polish"],
	"borders": ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
  "flag": "flags/pl.svg",
},
{
	"name": "Portugal",
	"capital": "Lisbon",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Portuguese"],
	"borders": ["ESP"],
  "flag": "flags/pt.svg",
},
{
	"name": "Republic of Kosovo",
	"capital": "Pristina",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Albanian", "Serbian"],
	"borders": ["ALB", "MKD", "MNE", "SRB"],
  "flag": "flags/koso.svg",
},
{
	"name": "Romania",
  "capital": "Bucharest",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Romanian"],
  "borders": ["BGR", "HUN", "MDA", "SRB", "UKR"],
  "flag": "flags/ro.svg",
},
{
	"name": "Russia",
	"capital": "Moscow",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Russian"],
	"borders": ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"],
  "flag": "flags/ru.svg",
},
{
	"name": "San Marino",
	"capital": "City of San Marino",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Italian"],
	"borders": ["ITA"],
  "flag": "flags/sm.svg",
},
{
	"name": "Serbia",
	"capital": "Belgrade",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Serbian"],
	"borders": ["BIH", "BGR", "HRV", "HUN", "KOS", "MKD", "MNE", "ROU"],
  "flag": "flags/rs.svg",
},
{
	"name": "Slovakia",
  "capital": "Bratislava",
  "region": "Europe",
  "subregion": "Eastern Europe",
  "language": ["Slovak"],
  "borders": ["AUT", "CZE", "HUN", "POL", "UKR"],
  "flag": "flags/sk.svg",
},
{
	"name": "Slovenia",
	"capital": "Ljubljana",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Slovene"],
	"borders": ["AUT", "HRV", "ITA", "HUN"],
  "flag": "flags/si.svg",
},
{
	"name": "Spain",
	"capital": "Madrid",
	"region": "Europe",
	"subregion": "Southern Europe",
	"language": ["Spanish", "Basque", "Catalan", "Galician", "Occitan"],
	"borders": ["AND", "FRA", "GIB", "PRT", "MAR"],
  "flag": "flags/es.svg",
},
{
	"name": "Sweden",
	"capital": "Stockholm",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["Swedish"],
	"borders": ["FIN", "NOR"],
  "flag": "flags/se.svg",
},
{
	"name": "Switzerland",
	"capital": "Bern",
	"region": "Europe",
  "subregion": "Western Europe",
  "language": ["German", "French", "Italian", "Romansh"],
  "borders": ["AUT", "FRA", "ITA", "LIE", "DEU"],
  "flag": "flags/ch.svg",
},
{
	"name": "Ukraine",
	"capital": "Kiev",
	"region": "Europe",
	"subregion": "Eastern Europe",
	"language": ["Ukrainian"],
	"borders": ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
  "flag": "flags/ua.svg",
},
{
	"name": "United Kingdom",
	"capital": "London",
	"region": "Europe",
	"subregion": "Northern Europe",
	"language": ["English"],
	"borders": ["IRL"],
  "flag": "flags/gb.svg",
},
]
