const COUNTRIES_AMERICAS = [

{
  "name": "Anguilla",
  "capital": "The Valley",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
  "flag": "flags/ai.svg",
},
{
  "name": "Antigua and Barbuda",
  "capital": "Saint John's",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
  "flag": "flags/ag.svg",
},
{
  "name": "Argentina",
  "capital": "Buenos Aires",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish"],
  "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
  "flag": "flags/ar.svg",
},
{
  "name": "Aruba",
  "capital": "Oranjestad",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Dutch", "Papiamento"],
  "borders": [],
  "flag": "flags/aw.svg",
},
{
  "name": "Bahamas",
  "capital": "Nassau",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
  "flag": "flags/bs.svg",
},
{
  "name": "Barbados",
  "capital": "Bridgetown",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
  "flag": "flags/bb.svg",
},
{
  "name": "Belize",
  "capital": "Belmopan",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["English"],
  "borders": ["GTM", "MEX"],
  "flag": "flags/bz.svg",
},
{
  "name": "Bermuda",
  "capital": "Hamilton",
  "region": "Americas",
  "subregion": "Northern America",
  "language": ["English"],
  "borders": [],
  "flag": "flags/bm.svg",
},
{
  "name": "Bolivia",
  "capital": "Sucre",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish", "Quechua", "Aymara", "Guaran\u00ed"],
  "borders": ["ARG", "BRA", "CHL", "PRY", "PRU"],
  "flag": "flags/bo.svg",
},
{
  "name": "Brazil",
  "capital": "Bras\u00edlia",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Portuguese"],
  "borders": ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
  "flag": "flags/br.svg",
},
{
	"name": "British Virgin Islands",
	"capital": "Road Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/vg.svg",
},
{
  "name": "Canada",
	"capital": "Ottawa",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["English", "French"],
	"borders": ["USA"],
  "flag": "flags/ca.svg",
},
{
	"name": "Cayman Islands",
	"capital": "George Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/ky.svg",
},
{
	"name": "Chile",
  "capital": "Santiago",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish"],
  "borders": ["ARG", "BOL", "PER"],
  "flag": "flags/cl.svg",
},
{
	"name": "Colombia",
	"capital": "Bogot\u00e1",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["BRA", "ECU", "PAN", "PER", "VEN"],
  "flag": "flags/co.svg",
},
{
	"name": "Costa Rica",
  "capital": "San Jos\u00e9",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["NIC", "PAN"],
  "flag": "flags/cr.svg",
},
{
	"name": "Cuba",
	"capital": "Havana",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Spanish"],
  "borders": [],
  "flag": "flags/cu.svg",
},
{
	"name": "Dominica",
	"capital": "Roseau",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/dm.svg",
},
{
	"name": "Dominican Republic",
	"capital": "Santo Domingo",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Spanish"],
  "borders": ["HTI"],
  "flag": "flags/do.svg",
},
{
	"name": "Ecuador",
	"capital": "Quito",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["COL", "PER"],
  "flag": "flags/ec.svg",
},
{
	"name": "El Salvador",
	"capital": "San Salvador",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["Castilian"],
  "borders": ["GTM", "HND"],
  "flag": "flags/sv.svg",
},
{
	"name": "Falkland Islands",
	"capital": "Stanley",
	"region": "Americas",
	"subregion": "South America",
	"language": ["English"],
	"borders": [],
  "flag": "flags/fk.svg",
},
{
	"name": "Grenada",
	"capital": "St. George's",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
  "flag": "flags/gd.svg",
},
{
	"name": "Guatemala",
  "capital": "Guatemala City",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["BLZ", "SLV", "HND", "MEX"],
  "flag": "flags/gt.svg",
},
{
	"name": "Guyana",
  "capital": "Georgetown",
  "region": "Americas",
  "subregion": "South America",
  "language": ["English"],
  "borders": ["BRA", "SUR", "VEN"],
  "flag": "flags/gy.svg",
},
{
  "name": "Haiti",
	"capital": "Port-au-Prince",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French", "Haitian Creole"],
	"borders": ["DOM"],
  "flag": "flags/ht.svg",
},
{
	"name": "Honduras",
	"capital": "Tegucigalpa",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["GTM", "SLV", "NIC"],
  "flag": "flags/hn.svg",
},
{
	"name": "Jamaica",
	"capital": "Kingston",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Jamaican English"],
	"borders": [],
  "flag": "flags/jm.svg",
},
{
	"name": "Mexico",
	"capital": "Mexico City",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["BLZ", "GTM", "USA"],
  "flag": "flags/mx.svg",
},
{
	"name": "Nicaragua",
	"capital": "Managua",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["CRI", "HND"],
  "flag": "flags/ni.svg",
},
{
	"name": "Panama",
  "capital": "Panama City",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["Spanish"],
  "borders": ["COL", "CRI"],
  "flag": "flags/pa.svg",
},
{
	"name": "Paraguay",
	"capital": "Asunci\u00f3n",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish", "Guaran\u00ed"],
	"borders": ["ARG", "BOL", "BRA"],
  "flag": "flags/py.svg",
},
{
	"name": "Peru",
	"capital": "Lima",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish", "Quechua", "Aymara"],
	"borders": ["BOL", "BRA", "CHL", "COL", "ECU"],
  "flag": "flags/pe.svg",
},
{
	"name": "Puerto Rico",
	"capital": "San Juan",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Spanish", "English"],
	"borders": [],
  "flag": "flags/pr.svg",
},
{
	"name": "Saint Kitts and Nevis",
	"capital": "Basseterre",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/kn.svg",
},
{
	"name": "Saint Lucia",
	"capital": "Castries",
	"region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
  "flag": "flags/lc.svg",
},
{
	"name": "Saint Vincent and the Grenadines",
	"capital": "Kingstown",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/vc.svg",
},
{
	"name": "Sint Maarten",
	"capital": "Philipsburg",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Dutch", "English"],
	"borders": ["MAF"],
  "flag": "flags/sx.svg",
},
{
	"name": "Suriname",
	"capital": "Paramaribo",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Dutch"],
	"borders": ["BRA", "GUF", "FRA", "GUY"],
  "flag": "flags/sr.svg",
},
{
	"name": "Trinidad and Tobago",
	"capital": "Port of Spain",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/tt.svg",
},
{
	"name": "United States",
	"capital": "Washington D.C.",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["English"],
	"borders": ["CAN", "MEX"],
  "flag": "flags/us.svg",
},
{
	"name": "United States Virgin Islands",
	"capital": "Charlotte Amalie",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
  "flag": "flags/vi.svg",
},
{
	"name": "Uruguay",
	"capital": "Montevideo",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["ARG", "BRA"],
  "flag": "flags/uy.svg",
},
{
	"name": "Venezuela",
	"capital": "Caracas",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["BRA", "COL", "GUY"],
  "flag": "flags/ve.svg",
}

]
