const COUNTRIES_AMERICAS = [

{
  "name": "Anguilla",
  "capital": "The Valley",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Antigua and Barbuda",
  "capital": "Saint John's",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Argentina",
  "capital": "Buenos Aires",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish"],
  "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
},
{
  "name": "Aruba",
  "capital": "Oranjestad",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Dutch", "Papiamento"],
  "borders": [],
},
{
  "name": "Ascension Island",
  "capital": "Georgetown",
  "region": "Americas",
  "subregion": "South America",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Bahamas",
  "capital": "Nassau",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Barbados",
  "capital": "Bridgetown",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Belize",
  "capital": "Belmopan",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["English"],
  "borders": ["GTM", "MEX"],
},
{
  "name": "Bermuda",
  "capital": "Hamilton",
  "region": "Americas",
  "subregion": "Northern America",
  "language": ["English"],
  "borders": [],
},
{
  "name": "Bolivia",
  "capital": "Sucre",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish", "Quechua", "Aymara", "Guaran\u00ed"],
  "borders": ["ARG", "BRA", "CHL", "PRY", "PRU"],
},
{
  "name": "Bonaire",
  "capital": "Kralendijk",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Dutch"],
  "borders": [],
},
{
  "name": "Brazil",
  "capital": "Bras\u00edlia",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Portuguese"],
  "borders": ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
},
{
	"name": "British Virgin Islands",
	"capital": "Road Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
  "name": "Canada",
	"capital": "Ottawa",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["English", "French"],
	"borders": ["USA"],
},
{
	"name": "Cayman Islands",
	"capital": "George Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Chile",
  "capital": "Santiago",
  "region": "Americas",
  "subregion": "South America",
  "language": ["Spanish"],
  "borders": ["ARG", "BOL", "PER"],
},
{
	"name": "Colombia",
	"capital": "Bogot\u00e1",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["BRA", "ECU", "PAN", "PER", "VEN"],
},
{
	"name": "Costa Rica",
  "capital": "San Jos\u00e9",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["NIC", "PAN"],
},
{
	"name": "Cuba",
	"capital": "Havana",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Spanish"],
  "borders": [],
},
{
	"name": "Cura\u00e7ao",
	"capital": "Willemstad",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Dutch", "Papiamentu", "English"],
	"borders": [],
},
{
	"name": "Dominica",
	"capital": "Roseau",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Dominican Republic",
	"capital": "Santo Domingo",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["Spanish"],
  "borders": ["HTI"],
},
{
	"name": "Ecuador",
	"capital": "Quito",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["COL", "PER"],
},
{
	"name": "El Salvador",
	"capital": "San Salvador",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["Castilian"],
  "borders": ["GTM", "HND"],
},
{
	"name": "Falkland Islands",
	"capital": "Stanley",
	"region": "Americas",
	"subregion": "South America",
	"language": ["English"],
	"borders": [],
},
{
  "name": "French Guiana",
  "capital": "Cayenne",
  "region": "Americas",
  "subregion": "South America",
  "language": ["French"],
	"borders": ["BRA", "SUR"],
},
{
	"name": "Grenada",
	"capital": "St. George's",
  "region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Guadeloupe",
  "capital": "Basse-Terre",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Guatemala",
  "capital": "Guatemala City",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["BLZ", "SLV", "HND", "MEX"],
},
{
	"name": "Guyana",
  "capital": "Georgetown",
  "region": "Americas",
  "subregion": "South America",
  "language": ["English"],
  "borders": ["BRA", "SUR", "VEN"],
},
{
  "name": "Haiti",
	"capital": "Port-au-Prince",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French", "Haitian Creole"],
	"borders": ["DOM"],
},
{
	"name": "Honduras",
	"capital": "Tegucigalpa",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["GTM", "SLV", "NIC"],
},
{
	"name": "Jamaica",
	"capital": "Kingston",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Jamaican English"],
	"borders": [],
},
{
	"name": "Martinique",
	"capital": "Fort-de-France",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Mexico",
	"capital": "Mexico City",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["BLZ", "GTM", "USA"],
},
{
	"name": "Montserrat",
	"capital": "Plymouth",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Nicaragua",
	"capital": "Managua",
	"region": "Americas",
	"subregion": "Central America",
	"language": ["Spanish"],
	"borders": ["CRI", "HND"],
},
{
	"name": "Panama",
  "capital": "Panama City",
  "region": "Americas",
  "subregion": "Central America",
  "language": ["Spanish"],
  "borders": ["COL", "CRI"],
},
{
	"name": "Paraguay",
	"capital": "Asunci\u00f3n",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish", "Guaran\u00ed"],
	"borders": ["ARG", "BOL", "BRA"],
},
{
	"name": "Peru",
	"capital": "Lima",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish", "Quechua", "Aymara"],
	"borders": ["BOL", "BRA", "CHL", "COL", "ECU"],
},
{
	"name": "Puerto Rico",
	"capital": "San Juan",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Spanish", "English"],
	"borders": [],
},
{
	"name": "Saint Barth\u00e9lemy",
	"capital": "Gustavia",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Saint Kitts and Nevis",
	"capital": "Basseterre",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Saint Lucia",
	"capital": "Castries",
	"region": "Americas",
  "subregion": "Caribbean",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Saint Martin",
	"capital": "Marigot",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["French"],
	"borders": ["SXM", "NLD"],
},
{
	"name": "Saint Pierre and Miquelon",
	"capital": "Saint-Pierre",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Saint Vincent and the Grenadines",
	"capital": "Kingstown",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Sint Maarten",
	"capital": "Philipsburg",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["Dutch", "English"],
	"borders": ["MAF"],
},
{
	"name": "South Georgia",
	"capital": "King Edward Point",
	"region": "Americas",
	"subregion": "South America",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Suriname",
	"capital": "Paramaribo",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Dutch"],
	"borders": ["BRA", "GUF", "FRA", "GUY"],
},
{
	"name": "Trinidad and Tobago",
	"capital": "Port of Spain",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Turks and Caicos Islands",
	"capital": "Cockburn Town",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "United States",
	"capital": "Washington D.C.",
	"region": "Americas",
	"subregion": "Northern America",
	"language": ["English"],
	"borders": ["CAN", "MEX"],
},
{
	"name": "United States Virgin Islands",
	"capital": "Charlotte Amalie",
	"region": "Americas",
	"subregion": "Caribbean",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Uruguay",
	"capital": "Montevideo",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["ARG", "BRA"],
},
{
	"name": "Venezuela",
	"capital": "Caracas",
	"region": "Americas",
	"subregion": "South America",
	"language": ["Spanish"],
	"borders": ["BRA", "COL", "GUY"],
}

]
