const COUNTRIES_OCEANIA = [

{
  "name": "American Samoa",
  "capital": "Pago Pago",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["English", "Samoan"],
  "borders": [],
},
{
  "name": "Australia",
  "capital": "Canberra",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Christmas Island",
	"capital": "Flying Fish Cove",
  "region": "Oceania",
  "subregion": "Australia and New Zealand",
  "language": ["English"],
  "borders": [],
},
{
	"name": "Cocos (Keeling) Islands",
	"capital": "West Island",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English"],
	"borders": [],
},
{
  "name": "Cook Islands",
	"capital": "Avarua",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["English", "Cook Islands M\u0101ori"],
	"borders": [],
},
{
	"name": "Fiji",
  "capital": "Suva",
  "region": "Oceania",
  "subregion": "Melanesia",
  "language": ["English", "Fijian", "Fiji Hindi"],
	"borders": [],
},
{
	"name": "French Polynesia",
	"capital": "Papeet\u0113",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["French"],
	"borders": [],
},
{
	"name": "Guam",
  "capital": "Hag\u00e5t\u00f1a",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["English", "Chamorro"],
	"borders": [],
},
{
	"name": "Kiribati",
  "capital": "South Tarawa",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Gilbertese"],
	"borders": [],
},
{
	"name": "Marshall Islands",
	"capital": "Majuro",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["Marshallese", "English"],
	"borders": [],
},
{
	"name": "Micronesia",
  "capital": "Palikir",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["English"],
  "borders": [],
},

{
	"name": "Nauru",
	"capital": "Yaren",
  "region": "Oceania",
  "subregion": "Micronesia",
  "language": ["Nauruan", "English"],
  "borders": [],
},
{
  "name": "New Caledonia",
	"capital": "Noum\u00e9a",
  "region": "Oceania",
  "subregion": "Melanesia",
  "language": ["French"],
  "borders": [],
},
{
	"name": "New Zealand",
	"capital": "Wellington",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English", "M\u0101ori", "New Zealand Sign Language"],
	"borders": [],
},
{
	"name": "Niue",
	"capital": "Alofi",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Niuean", "English"],
	"borders": [],
},
{
	"name": "Norfolk Island",
	"capital": "Kingston",
	"region": "Oceania",
	"subregion": "Australia and New Zealand",
	"language": ["English", "Norfuk"],
	"borders": [],
},
{
	"name": "Northern Mariana Islands",
	"capital": "Saipan",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Chamorro", "Carolinian"],
	"borders": [],
},
{
  "name": "Palau",
	"capital": "Ngerulmud",
	"region": "Oceania",
	"subregion": "Micronesia",
	"language": ["English", "Palauan"],
	"borders": [],
},
{
	"name": "Papua New Guinea",
	"capital": "Port Moresby",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["Hiri Motu", "Tok Pisin", "English"],
	"borders": ["IDN"],
},
{
	"name": "Pitcairn Islands",
	"capital": "Adamstown",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["English"],
	"borders": [],
},
{
	"name": "Samoa",
	"capital": "Apia",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Samoan", "English"],
	"borders": [],
},
{
	"name": "Solomon Islands",
	"capital": "Honiara",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["English"],
	"borders": [],
},
{
  "name": "Tokelau",
	"capital": "Fakaofo",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["Tokelauan", "English", "Samoan"],
  "borders": [],
},
{
	"name": "Tonga",
  "capital": "Nuku'alofa",
  "region": "Oceania",
  "subregion": "Polynesia",
  "language": ["Tongan", "English"],
  "borders": [],
},
{
	"name": "Tuvalu",
	"capital": "Funafuti",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["Tuvaluan", "English"],
	"borders": [],
},
{
	"name": "Vanuatu",
	"capital": "Port Vila",
	"region": "Oceania",
	"subregion": "Melanesia",
	"language": ["Bislama", "French", "English"],
	"borders": [],
},
{
	"name": "Wallis and Futuna",
	"capital": "Mata-Utu",
	"region": "Oceania",
	"subregion": "Polynesia",
	"language": ["French"],
	"borders": [],
}

]
